#!/usr/bin/python3
# jokes shell v0.00
# author: jks
""" Language written in python """
import sys
from jokes.core.console import Console

if len(sys.argv) == 1:
    shell = Console()
    shell.run()

elif len(sys.argv) == 2:
    shell = Console(mode='script')
    shell.run(sys.argv[1])